before:
  hooks:
    - go mod tidy
builds:
  - id: urlmanager
    main: ./cmd/url-manager
    binary: urlmanager
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.BuildName=urlmanager -X main.BuildTag={{.Version}} -extldflags '-static'

archives:
  - id: urlmanager
    builds:
      - urlmanager
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: robotomize
    name: url-manager